language: rust
rust: 1.32.0
sudo: true
cache:
  timeout: 1024
  directories:
    - $HOME/.cargo

if: 'branch = master OR type != push OR fork = true OR tag =~ ^v'

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  include:
    - os: osx
      install:
        - cargo fmt --version || rustup component add rustfmt
        - cargo clippy --version || rustup component add clippy
    - os: linux

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo fmt -- --check; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo clippy; fi
- cargo test

before_cache:
- rm -rf $HOME/.cargo/registry
